version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    build: ./mysql
    volumes:
      - ${PWD}/mysql/data:/var/lib/mysql
      - ${PWD}/mysql/sql:/opt/sql
      # for init and backup
      - ${PWD}/mysql/init:/docker-entrypoint-initdb.d/
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=mysql"
      - "TZ=Asia/Shanghai"
    ports:
      - "3306:3306"
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
